### ISSUE TITLE
Invalid code isn't handled correctly

### ISSUE THREAD

**Issue by MrJul** [KathleenDollard/RoslynDOM#101]
Parsing an invalid code such as simply `foo` raises a `NullReferenceException` in `StructuredDocumentationFactory` because `parentAsHasSymbol.Symbol` is `null`.

**Comment by KathleenDollard** [comment]
Julien, 

 

Wanted to let you know I am looking at this. 

 

Kathleen

**Comment by MrJul** [comment]
Thanks Kathleen!
I sent you a pull request (#102) fixing this already.
