### ISSUE TITLE
Probable typo in RDomParameter

### ISSUE THREAD

**Issue by wwrafter** [KathleenDollard/RoslynDOM#97]
First constructor:
      public RDomParameter( string name, string typeName,
                      int ordinal = 0, bool isOut = false, bool isRef = false,
                      bool isParamArray = false)
          : this(name, name, null, 
                LiteralKind.Unknown, null, ordinal, isOut, isRef, isParamArray)
      { }

This:
          : this(name, name, null, 
Should probably be:
          : this(name, typeName, null,

**Comment by KathleenDollard** [comment]
Fixed
